[tool.poetry]
name = "poetry-science-env"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
include = ["pyproject.toml"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.23.4"
pandas = "^1.5.1"
scipy = "^1.10.1"
matplotlib = "^3.7.1"
scikit-learn = "^1.2.2"
networkx = "^3.0"
numba = "^0.56.4"
awswrangler = "^3.0.0"
boto3 = "^1.24.59"
s3fs = "^2023.4.0"
ipython = "^8.12.2"
contexttimer = "^0.3.3"
seaborn = "^0.12.2"
tqdm = "^4.65.0"
jupyter = "^1.0.0"
ms2-inference = {git = "https://github.com/enveda/ms2-inference.git", rev = "gv-dev"}
specformers = {git = "https://github.com/enveda/specformers.git", rev = "gv-dev"}
molecular-library-search = {git = "https://github.com/enveda/molecular-library-search.git", rev = "gv-dev"}
metabolomics = {git = "https://github.com/enveda/metabolomics.git", rev = "gv-dev"}
openpyxl = "^3.1.2"
pyteomics = "^4.7.1"
lxml = "^5.2.1"
deprecated = "^1.2.14"
misosoup-client = {git = "https://github.com/enveda/misosoup-client.git"}
spectral-inference-zoo = {git = "https://github.com/enveda/spectral-inference-zoo.git", rev = "gv-dev"}